{{/*
  *  Standalone Pod Render
  *
*/}}
{{- define "ph.pod.artifact" -}}

apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
spec: {{ include "ph.pod.render" . | nindent 2}}

{{- end -}}

{{/*
  *  Render for pods
  *
*/}}

{{- define "ph.pod.render" -}}

{{ include "ph.init_containers.render" . }}

containers:
  {{- range $c := .containers }}
  {{ include "ph.container.render" $c | nindent 2}}
  {{- end }}

imagePullSecrets: 
  {{ range $v := default (list) .imagePullSecrets }}
  - name: {{ $v }}
  {{ end }}


volumes: {{ include "ph.pod_volumes.render" . | nindent 2 }}

{{- end -}}

{{/*
  *  Render for pods
  *
*/}}
{{- define "ph.init_containers.render" -}}

{{- if hasKey . "init_containers" -}}

{{ $_render_init_containers := (default "ph.container.render" .render_init_container) }}

init_containers:
  {{- range $c := .init_containers }}
  {{ include $_render_init_containers $c | nindent 2}}
  {{- end -}}

{{- end -}}

{{- end -}}

