{{- define "ph.ingress.render" -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ required "A name is required for an ingress rule!" .name }}
  annotations: {{ default (dict) .annotations | toYaml | nindent 4 }}

{{ include "ph.ingress_spec.render" . }}

{{- end -}}

{{- define "ph.ingress_spec.render" -}}

spec:
  {{- if hasKey . "tls" }}
  tls:
    {{ range $tls := .tls }}
    {{ if not (kindIs "slice" $tls.hosts) }}
    {{ fail "[Ingres:render] tls' hosts must be a list" }}
    {{ end }}
    hosts: {{ $tls.hosts | toYaml | nindent 6 }}
      
    secretName: {{ $tls.secretName }}
    {{ end }}
  {{ end }}
  rules: 
  {{- if hasKey . "rules" }}

  {{- else }}
  - host: {{ (default "*" .host) }}
    http:
    {{ include "ph.ingress_rules.single.render" . | indent 6}}
      
  {{- end }}

{{- end -}}

{{- define "ph.ingress_rules.single.render" }}

paths: 
{{ range $rule := .rules_path }}
- path: {{ $rule.path }}
  pathType: {{ default "Prefix" $rule.pathType }}
  backend:
    serviceName: {{ $rule.service }}
    servicePort: {{ $rule.port }}
{{ end }}

{{- end -}}
