{{- define "ph.ingress.render" -}}

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ required "A name is required for an ingress rule!" .name }}
  annotations: {{ default (dict) .annotations | toYaml | nindent 4 }}

{{ include "ph.ingress_spec.render" . }}

{{- end -}}

{{- define "ph.ingress_spec.render" -}}

spec:
  rules: 
  - http:
      paths: 
      {{ range $rule := .rules_path }}
      - path: {{ $rule.path }}
        pathType: {{ default "Prefix" $rule.pathType }}
        backend:
          serviceName: {{ $rule.service }}
          servicePort: {{ $rule.port }}
      {{ end }}

{{- end -}}
