{{- define "ph.pod.artifact" -}}

apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
spec: {{ include "ph.pod.render" . | nindent 2}}

{{- end -}}


{{- define "ph.pod.render" -}}

containers:
  {{- range $c := .containers }}
  {{ include "ph.container.render" $c | nindent 2}}
  {{- end -}}

{{ include "ph.image_pull_secrets.render" . }}
{{ include "ph.init_containers.render" . }}


{{- end -}}

{{- define "ph.image_pull_secrets.render" -}}

{{- if hasKey . "image_pull_secrets" -}}

image_pull_secrets: 
  {{- range $v := default (list) .image_pull_secrets }}
  - name: {{ $v }}
  {{- end -}}

{{- end -}}

{{- end -}}


{{- define "ph.init_containers.render" -}}

{{- if hasKey . "init_containers" -}}

{{ $_render_init_containers := (default "ph.container.render" .render_init_container) }}

init_containers:
  {{- range $c := .init_containers }}
  {{ include $_render_init_containers $c | nindent 2}}
  {{- end -}}

{{- end -}}

{{- end -}}
