name: release-pipeline

on:
  release:
    types: [released]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pack new chart release
        run: |
          helm package . -d docs/
      - name: Rebuild index
        run: |
          cd docs/ && helm repo index . 
